### ISSUE TITLE
Use `sf` instead of `sp`

### ISSUE THREAD

**Issue by lambdamoses** [JEFworks-Lab/CRAWDAD#22]
I saw your paper, super cool! I noticed that your package imports `sp`. Note that the legacy packages underpinning `sp` will retire and be archived from CRAN this month. https://r-spatial.org/r/2023/05/15/evolution4.html Please switch to `sf` to future-proof your package.

**Comment by rafaeldossantospeixoto** [comment]
Hello! Thanks for the suggestion! I changed our toSP function to our new toSF function. Now CRAWDAD does not depend on the sp package anymore. Thank you again for your contribution!
